# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TS-Boilerplate CI

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  format:
    name: Code Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Run formatting check
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          prettier: true

  client:
    name: Web Client - Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Yarn install
        working-directory: ./src/client
        run: yarn install --frozen-lockfile

      - name: Run tests
        working-directory: ./src/client
        run: yarn test

  server:
    name: Server - Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Yarn install
        working-directory: ./src
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        # Get all changed files, filter to only .js, .ts, .tsx, and lint them
        run: yarn lint

      - name: Run tests
        working-directory: ./src
        run: yarn test

      - name: Compile TypeScript
        working-directory: ./src
        run: yarn build
